export const PERMISSIONS = [
  'pos:view',
  'pos:create',
  'pos:update',
  'pos:delete',
  'pos:refund',
  'post:return',
  'products:view',
  'products:create',
  'products:update',
  'products:delete',
  'categories:view',
  'categories:create',
  'categories:update',
  'categories:delete',
  'inventory:view',
  'inventory:view-sales-history',
  'inventory:view-movement-history',
  'inventory:create-adjustment',
  'inventory:purchase:view',
  'inventory:purchase:create',
  'inventory:purchase:update',
  'inventory:purchase:delete',
  'dashboard:view',
] as const
export type Permission = (typeof PERMISSIONS)[number]
