export const PERMISSIONS = [
	"members:view",
	"members:create",
	"members:update",
	"members:delete",
	"members:freeze",
	"members:unfreeze",
	"members:terminate",
	"members:view-profile",
	"attendance:view",
	"plans:view",
	"plans:create",
	"plans:update",
	"plans:delete",
	"dashboard:view",
	"chart-of-accounts:view",
	"chart-of-accounts:create",
	"chart-of-accounts:update",
	"chart-of-accounts:delete",
	"payments:view",
	"payments:create",
	"payments:update",
	"payments:delete",
	"payments:view-pending-payments",
	"expenses:view",
	"expenses:create",
	"expenses:update",
	"expenses:delete",
	"journal-entries:view",
	"journal-entries:create",
	"journal-entries:update",
	"journal-entries:delete",
] as const;
export type Permission = (typeof PERMISSIONS)[number];
