/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteRouteImport } from './routes/member/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberDashboardRouteImport } from './routes/member/dashboard'
import { Route as AppUnauthorizedRouteImport } from './routes/app/unauthorized'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AppUsersRouteRouteImport } from './routes/app/users/route'
import { Route as AppPlansRouteRouteImport } from './routes/app/plans/route'
import { Route as AppMembersRouteRouteImport } from './routes/app/members/route'
import { Route as AppUsersIndexRouteImport } from './routes/app/users/index'
import { Route as AppPlansIndexRouteImport } from './routes/app/plans/index'
import { Route as AppMembersIndexRouteImport } from './routes/app/members/index'
import { Route as AppUsersNewRouteImport } from './routes/app/users/new'
import { Route as AppPlansNewRouteImport } from './routes/app/plans/new'
import { Route as AppMembersNewRouteImport } from './routes/app/members/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppUsersRolesIndexRouteImport } from './routes/app/users/roles.index'
import { Route as AppUsersRolesNewRouteImport } from './routes/app/users/roles.new'
import { Route as AppUsersUserIdResetRouteImport } from './routes/app/users/$userId.reset'
import { Route as AppUsersUserIdEditRouteImport } from './routes/app/users/$userId.edit'
import { Route as AppPlansPlanIdEditRouteImport } from './routes/app/plans/$planId/edit'
import { Route as AppMembersMemberIdProfileRouteImport } from './routes/app/members/$memberId.profile'
import { Route as AppMembersMemberIdEditRouteImport } from './routes/app/members/$memberId.edit'
import { Route as AppUsersRolesRoleIdEditRouteImport } from './routes/app/users/roles.$roleId.edit'

const MemberRouteRoute = MemberRouteRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberDashboardRoute = MemberDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MemberRouteRoute,
} as any)
const AppUnauthorizedRoute = AppUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AppUsersRouteRoute = AppUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlansRouteRoute = AppPlansRouteRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMembersRouteRoute = AppMembersRouteRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlansRouteRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMembersRouteRoute,
} as any)
const AppUsersNewRoute = AppUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppPlansNewRoute = AppPlansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPlansRouteRoute,
} as any)
const AppMembersNewRoute = AppMembersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppMembersRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRolesIndexRoute = AppUsersRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppUsersRolesNewRoute = AppUsersRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppUsersUserIdResetRoute = AppUsersUserIdResetRouteImport.update({
  id: '/$userId/reset',
  path: '/$userId/reset',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppUsersUserIdEditRoute = AppUsersUserIdEditRouteImport.update({
  id: '/$userId/edit',
  path: '/$userId/edit',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppPlansPlanIdEditRoute = AppPlansPlanIdEditRouteImport.update({
  id: '/$planId/edit',
  path: '/$planId/edit',
  getParentRoute: () => AppPlansRouteRoute,
} as any)
const AppMembersMemberIdProfileRoute =
  AppMembersMemberIdProfileRouteImport.update({
    id: '/$memberId/profile',
    path: '/$memberId/profile',
    getParentRoute: () => AppMembersRouteRoute,
  } as any)
const AppMembersMemberIdEditRoute = AppMembersMemberIdEditRouteImport.update({
  id: '/$memberId/edit',
  path: '/$memberId/edit',
  getParentRoute: () => AppMembersRouteRoute,
} as any)
const AppUsersRolesRoleIdEditRoute = AppUsersRolesRoleIdEditRouteImport.update({
  id: '/roles/$roleId/edit',
  path: '/roles/$roleId/edit',
  getParentRoute: () => AppUsersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/app/members': typeof AppMembersRouteRouteWithChildren
  '/app/plans': typeof AppPlansRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/members/new': typeof AppMembersNewRoute
  '/app/plans/new': typeof AppPlansNewRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/app/members/': typeof AppMembersIndexRoute
  '/app/plans/': typeof AppPlansIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/app/members/$memberId/profile': typeof AppMembersMemberIdProfileRoute
  '/app/plans/$planId/edit': typeof AppPlansPlanIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/users/$userId/reset': typeof AppUsersUserIdResetRoute
  '/app/users/roles/new': typeof AppUsersRolesNewRoute
  '/app/users/roles': typeof AppUsersRolesIndexRoute
  '/app/users/roles/$roleId/edit': typeof AppUsersRolesRoleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/members/new': typeof AppMembersNewRoute
  '/app/plans/new': typeof AppPlansNewRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/app/members': typeof AppMembersIndexRoute
  '/app/plans': typeof AppPlansIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/app/members/$memberId/profile': typeof AppMembersMemberIdProfileRoute
  '/app/plans/$planId/edit': typeof AppPlansPlanIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/users/$userId/reset': typeof AppUsersUserIdResetRoute
  '/app/users/roles/new': typeof AppUsersRolesNewRoute
  '/app/users/roles': typeof AppUsersRolesIndexRoute
  '/app/users/roles/$roleId/edit': typeof AppUsersRolesRoleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/app/members': typeof AppMembersRouteRouteWithChildren
  '/app/plans': typeof AppPlansRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/members/new': typeof AppMembersNewRoute
  '/app/plans/new': typeof AppPlansNewRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/app/members/': typeof AppMembersIndexRoute
  '/app/plans/': typeof AppPlansIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/app/members/$memberId/profile': typeof AppMembersMemberIdProfileRoute
  '/app/plans/$planId/edit': typeof AppPlansPlanIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/users/$userId/reset': typeof AppUsersUserIdResetRoute
  '/app/users/roles/new': typeof AppUsersRolesNewRoute
  '/app/users/roles/': typeof AppUsersRolesIndexRoute
  '/app/users/roles/$roleId/edit': typeof AppUsersRolesRoleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/member'
    | '/app/members'
    | '/app/plans'
    | '/app/users'
    | '/forgot-password'
    | '/sign-in'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/unauthorized'
    | '/member/dashboard'
    | '/api/auth/$'
    | '/app/members/new'
    | '/app/plans/new'
    | '/app/users/new'
    | '/app/members/'
    | '/app/plans/'
    | '/app/users/'
    | '/app/members/$memberId/edit'
    | '/app/members/$memberId/profile'
    | '/app/plans/$planId/edit'
    | '/app/users/$userId/edit'
    | '/app/users/$userId/reset'
    | '/app/users/roles/new'
    | '/app/users/roles'
    | '/app/users/roles/$roleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/member'
    | '/forgot-password'
    | '/sign-in'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/unauthorized'
    | '/member/dashboard'
    | '/api/auth/$'
    | '/app/members/new'
    | '/app/plans/new'
    | '/app/users/new'
    | '/app/members'
    | '/app/plans'
    | '/app/users'
    | '/app/members/$memberId/edit'
    | '/app/members/$memberId/profile'
    | '/app/plans/$planId/edit'
    | '/app/users/$userId/edit'
    | '/app/users/$userId/reset'
    | '/app/users/roles/new'
    | '/app/users/roles'
    | '/app/users/roles/$roleId/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/app'
    | '/member'
    | '/app/members'
    | '/app/plans'
    | '/app/users'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/unauthorized'
    | '/member/dashboard'
    | '/api/auth/$'
    | '/app/members/new'
    | '/app/plans/new'
    | '/app/users/new'
    | '/app/members/'
    | '/app/plans/'
    | '/app/users/'
    | '/app/members/$memberId/edit'
    | '/app/members/$memberId/profile'
    | '/app/plans/$planId/edit'
    | '/app/users/$userId/edit'
    | '/app/users/$userId/reset'
    | '/app/users/roles/new'
    | '/app/users/roles/'
    | '/app/users/roles/$roleId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  MemberRouteRoute: typeof MemberRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/dashboard': {
      id: '/member/dashboard'
      path: '/dashboard'
      fullPath: '/member/dashboard'
      preLoaderRoute: typeof MemberDashboardRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/app/unauthorized': {
      id: '/app/unauthorized'
      path: '/unauthorized'
      fullPath: '/app/unauthorized'
      preLoaderRoute: typeof AppUnauthorizedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/plans/': {
      id: '/app/plans/'
      path: '/'
      fullPath: '/app/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/app/members/': {
      id: '/app/members/'
      path: '/'
      fullPath: '/app/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppMembersRouteRoute
    }
    '/app/users/new': {
      id: '/app/users/new'
      path: '/new'
      fullPath: '/app/users/new'
      preLoaderRoute: typeof AppUsersNewRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/plans/new': {
      id: '/app/plans/new'
      path: '/new'
      fullPath: '/app/plans/new'
      preLoaderRoute: typeof AppPlansNewRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/app/members/new': {
      id: '/app/members/new'
      path: '/new'
      fullPath: '/app/members/new'
      preLoaderRoute: typeof AppMembersNewRouteImport
      parentRoute: typeof AppMembersRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users/roles/': {
      id: '/app/users/roles/'
      path: '/roles'
      fullPath: '/app/users/roles'
      preLoaderRoute: typeof AppUsersRolesIndexRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/users/roles/new': {
      id: '/app/users/roles/new'
      path: '/roles/new'
      fullPath: '/app/users/roles/new'
      preLoaderRoute: typeof AppUsersRolesNewRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/users/$userId/reset': {
      id: '/app/users/$userId/reset'
      path: '/$userId/reset'
      fullPath: '/app/users/$userId/reset'
      preLoaderRoute: typeof AppUsersUserIdResetRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/users/$userId/edit': {
      id: '/app/users/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/app/users/$userId/edit'
      preLoaderRoute: typeof AppUsersUserIdEditRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/plans/$planId/edit': {
      id: '/app/plans/$planId/edit'
      path: '/$planId/edit'
      fullPath: '/app/plans/$planId/edit'
      preLoaderRoute: typeof AppPlansPlanIdEditRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/app/members/$memberId/profile': {
      id: '/app/members/$memberId/profile'
      path: '/$memberId/profile'
      fullPath: '/app/members/$memberId/profile'
      preLoaderRoute: typeof AppMembersMemberIdProfileRouteImport
      parentRoute: typeof AppMembersRouteRoute
    }
    '/app/members/$memberId/edit': {
      id: '/app/members/$memberId/edit'
      path: '/$memberId/edit'
      fullPath: '/app/members/$memberId/edit'
      preLoaderRoute: typeof AppMembersMemberIdEditRouteImport
      parentRoute: typeof AppMembersRouteRoute
    }
    '/app/users/roles/$roleId/edit': {
      id: '/app/users/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/app/users/roles/$roleId/edit'
      preLoaderRoute: typeof AppUsersRolesRoleIdEditRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppMembersRouteRouteChildren {
  AppMembersNewRoute: typeof AppMembersNewRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
  AppMembersMemberIdEditRoute: typeof AppMembersMemberIdEditRoute
  AppMembersMemberIdProfileRoute: typeof AppMembersMemberIdProfileRoute
}

const AppMembersRouteRouteChildren: AppMembersRouteRouteChildren = {
  AppMembersNewRoute: AppMembersNewRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
  AppMembersMemberIdEditRoute: AppMembersMemberIdEditRoute,
  AppMembersMemberIdProfileRoute: AppMembersMemberIdProfileRoute,
}

const AppMembersRouteRouteWithChildren = AppMembersRouteRoute._addFileChildren(
  AppMembersRouteRouteChildren,
)

interface AppPlansRouteRouteChildren {
  AppPlansNewRoute: typeof AppPlansNewRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
  AppPlansPlanIdEditRoute: typeof AppPlansPlanIdEditRoute
}

const AppPlansRouteRouteChildren: AppPlansRouteRouteChildren = {
  AppPlansNewRoute: AppPlansNewRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
  AppPlansPlanIdEditRoute: AppPlansPlanIdEditRoute,
}

const AppPlansRouteRouteWithChildren = AppPlansRouteRoute._addFileChildren(
  AppPlansRouteRouteChildren,
)

interface AppUsersRouteRouteChildren {
  AppUsersNewRoute: typeof AppUsersNewRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppUsersUserIdEditRoute: typeof AppUsersUserIdEditRoute
  AppUsersUserIdResetRoute: typeof AppUsersUserIdResetRoute
  AppUsersRolesNewRoute: typeof AppUsersRolesNewRoute
  AppUsersRolesIndexRoute: typeof AppUsersRolesIndexRoute
  AppUsersRolesRoleIdEditRoute: typeof AppUsersRolesRoleIdEditRoute
}

const AppUsersRouteRouteChildren: AppUsersRouteRouteChildren = {
  AppUsersNewRoute: AppUsersNewRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppUsersUserIdEditRoute: AppUsersUserIdEditRoute,
  AppUsersUserIdResetRoute: AppUsersUserIdResetRoute,
  AppUsersRolesNewRoute: AppUsersRolesNewRoute,
  AppUsersRolesIndexRoute: AppUsersRolesIndexRoute,
  AppUsersRolesRoleIdEditRoute: AppUsersRolesRoleIdEditRoute,
}

const AppUsersRouteRouteWithChildren = AppUsersRouteRoute._addFileChildren(
  AppUsersRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppMembersRouteRoute: typeof AppMembersRouteRouteWithChildren
  AppPlansRouteRoute: typeof AppPlansRouteRouteWithChildren
  AppUsersRouteRoute: typeof AppUsersRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUnauthorizedRoute: typeof AppUnauthorizedRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppMembersRouteRoute: AppMembersRouteRouteWithChildren,
  AppPlansRouteRoute: AppPlansRouteRouteWithChildren,
  AppUsersRouteRoute: AppUsersRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUnauthorizedRoute: AppUnauthorizedRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface MemberRouteRouteChildren {
  MemberDashboardRoute: typeof MemberDashboardRoute
}

const MemberRouteRouteChildren: MemberRouteRouteChildren = {
  MemberDashboardRoute: MemberDashboardRoute,
}

const MemberRouteRouteWithChildren = MemberRouteRoute._addFileChildren(
  MemberRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  MemberRouteRoute: MemberRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
