/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteRouteImport } from './routes/member/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberLoginRouteImport } from './routes/member/login'
import { Route as MemberDashboardRouteImport } from './routes/member/dashboard'
import { Route as AppUnauthorizedRouteImport } from './routes/app/unauthorized'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppJournalEntriesRouteImport } from './routes/app/journal-entries'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AppUsersRouteRouteImport } from './routes/app/users/route'
import { Route as AppSuppliersRouteRouteImport } from './routes/app/suppliers/route'
import { Route as AppReceiptsRouteRouteImport } from './routes/app/receipts/route'
import { Route as AppPlansRouteRouteImport } from './routes/app/plans/route'
import { Route as AppPaymentsRouteRouteImport } from './routes/app/payments/route'
import { Route as AppMembersRouteRouteImport } from './routes/app/members/route'
import { Route as AppFinancialYearsRouteRouteImport } from './routes/app/financial-years/route'
import { Route as AppExpensesRouteRouteImport } from './routes/app/expenses/route'
import { Route as AppChartOfAccountsRouteRouteImport } from './routes/app/chart-of-accounts/route'
import { Route as AppBillsRouteRouteImport } from './routes/app/bills/route'
import { Route as AppBankingsRouteRouteImport } from './routes/app/bankings/route'
import { Route as AppUsersIndexRouteImport } from './routes/app/users/index'
import { Route as AppSuppliersIndexRouteImport } from './routes/app/suppliers/index'
import { Route as AppReceiptsIndexRouteImport } from './routes/app/receipts/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppPlansIndexRouteImport } from './routes/app/plans/index'
import { Route as AppPaymentsIndexRouteImport } from './routes/app/payments/index'
import { Route as AppMembersIndexRouteImport } from './routes/app/members/index'
import { Route as AppFinancialYearsIndexRouteImport } from './routes/app/financial-years/index'
import { Route as AppExpensesIndexRouteImport } from './routes/app/expenses/index'
import { Route as AppCommunicationIndexRouteImport } from './routes/app/communication/index'
import { Route as AppChartOfAccountsIndexRouteImport } from './routes/app/chart-of-accounts/index'
import { Route as AppBillsIndexRouteImport } from './routes/app/bills/index'
import { Route as AppAttendancesIndexRouteImport } from './routes/app/attendances/index'
import { Route as AppActivityLogsIndexRouteImport } from './routes/app/activity-logs/index'
import { Route as ApiMockApiIndexRouteImport } from './routes/api/mock-api/index'
import { Route as ApiInngestIndexRouteImport } from './routes/api/inngest/index'
import { Route as AppUsersNewRouteImport } from './routes/app/users/new'
import { Route as AppSuppliersNewRouteImport } from './routes/app/suppliers/new'
import { Route as AppReceiptsNewRouteImport } from './routes/app/receipts/new'
import { Route as AppPlansNewRouteImport } from './routes/app/plans/new'
import { Route as AppPaymentsNewRouteImport } from './routes/app/payments/new'
import { Route as AppMembersNewRouteImport } from './routes/app/members/new'
import { Route as AppFinancialYearsNewRouteImport } from './routes/app/financial-years/new'
import { Route as AppExpensesNewRouteImport } from './routes/app/expenses/new'
import { Route as AppChartOfAccountsNewRouteImport } from './routes/app/chart-of-accounts/new'
import { Route as AppBillsNewRouteImport } from './routes/app/bills/new'
import { Route as AppBankingsReconcilliationRouteImport } from './routes/app/bankings/reconcilliation'
import { Route as AppBankingsClearRouteImport } from './routes/app/bankings/clear'
import { Route as ApiUploadsExpenseAttachmentRouteImport } from './routes/api/uploads/expense-attachment'
import { Route as ApiCommunicationsGetMembersRouteImport } from './routes/api/communications/get-members'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppUsersRolesRouteRouteImport } from './routes/app/users/roles.route'
import { Route as AppReportsFinanceRouteRouteImport } from './routes/app/reports/finance/route'
import { Route as AppExpensesExpenseIdRouteRouteImport } from './routes/app/expenses/$expenseId/route'
import { Route as AppBankingsPostingsRouteRouteImport } from './routes/app/bankings/postings/route'
import { Route as AppUsersRolesIndexRouteImport } from './routes/app/users/roles.index'
import { Route as AppReportsFinanceIndexRouteImport } from './routes/app/reports/finance/index'
import { Route as AppBankingsPostingsIndexRouteImport } from './routes/app/bankings/postings/index'
import { Route as ApiCronDailyIndexRouteImport } from './routes/api/cron/daily/index'
import { Route as AppUsersRolesNewRouteImport } from './routes/app/users/roles.new'
import { Route as AppUsersUserIdResetRouteImport } from './routes/app/users/$userId.reset'
import { Route as AppUsersUserIdEditRouteImport } from './routes/app/users/$userId.edit'
import { Route as AppSuppliersSupplierIdEditRouteImport } from './routes/app/suppliers/$supplierId/edit'
import { Route as AppReceiptsReceiptIdDetailsRouteImport } from './routes/app/receipts/$receiptId/details'
import { Route as AppPlansPlanIdViewMembersRouteImport } from './routes/app/plans/$planId/view-members'
import { Route as AppPlansPlanIdRevenueRouteImport } from './routes/app/plans/$planId/revenue'
import { Route as AppPlansPlanIdEditRouteImport } from './routes/app/plans/$planId/edit'
import { Route as AppPaymentsPaymentIdEditRouteImport } from './routes/app/payments/$paymentId/edit'
import { Route as AppPaymentsPaymentIdDetailsRouteImport } from './routes/app/payments/$paymentId/details'
import { Route as AppMembersMemberIdProfileRouteImport } from './routes/app/members/$memberId.profile'
import { Route as AppMembersMemberIdEditRouteImport } from './routes/app/members/$memberId.edit'
import { Route as AppFinancialYearsFinancialYearIdEditRouteImport } from './routes/app/financial-years/$financialYearId/edit'
import { Route as AppExpensesExpenseIdViewRouteImport } from './routes/app/expenses/$expenseId/view'
import { Route as AppExpensesExpenseIdEditRouteImport } from './routes/app/expenses/$expenseId/edit'
import { Route as AppChartOfAccountsAccountIdEditRouteImport } from './routes/app/chart-of-accounts/$accountId.edit'
import { Route as AppBillsBillIdEditRouteImport } from './routes/app/bills/$billId/edit'
import { Route as AppBankingsPostingsNewRouteImport } from './routes/app/bankings/postings/new'
import { Route as AppReportsFinanceTrialBalanceIndexRouteImport } from './routes/app/reports/finance/trial-balance/index'
import { Route as AppReportsFinanceReceiptsIndexRouteImport } from './routes/app/reports/finance/receipts/index'
import { Route as AppReportsFinancePaymentsIndexRouteImport } from './routes/app/reports/finance/payments/index'
import { Route as AppReportsFinanceInvoicesIndexRouteImport } from './routes/app/reports/finance/invoices/index'
import { Route as AppReportsFinanceIncomeStatementIndexRouteImport } from './routes/app/reports/finance/income-statement/index'
import { Route as AppReportsFinanceExpensesIndexRouteImport } from './routes/app/reports/finance/expenses/index'
import { Route as AppReportsFinanceBankingIndexRouteImport } from './routes/app/reports/finance/banking/index'
import { Route as AppUsersRolesRoleIdEditRouteImport } from './routes/app/users/roles.$roleId.edit'
import { Route as AppBankingsPostingsPostingIdEditRouteImport } from './routes/app/bankings/postings/$postingId/edit'
import { Route as ApiPaymentsPabfcStkCallbackRouteImport } from './routes/api/payments/pabfc/stk/callback'
import { Route as ApiPaymentsPabfcC2bValidateRouteImport } from './routes/api/payments/pabfc/c2b/validate'
import { Route as ApiPaymentsPabfcC2bConfRouteImport } from './routes/api/payments/pabfc/c2b/conf'

const MemberRouteRoute = MemberRouteRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberLoginRoute = MemberLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberDashboardRoute = MemberDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MemberRouteRoute,
} as any)
const AppUnauthorizedRoute = AppUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJournalEntriesRoute = AppJournalEntriesRouteImport.update({
  id: '/journal-entries',
  path: '/journal-entries',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AppUsersRouteRoute = AppUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuppliersRouteRoute = AppSuppliersRouteRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReceiptsRouteRoute = AppReceiptsRouteRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlansRouteRoute = AppPlansRouteRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPaymentsRouteRoute = AppPaymentsRouteRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMembersRouteRoute = AppMembersRouteRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinancialYearsRouteRoute = AppFinancialYearsRouteRouteImport.update({
  id: '/financial-years',
  path: '/financial-years',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpensesRouteRoute = AppExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChartOfAccountsRouteRoute = AppChartOfAccountsRouteRouteImport.update({
  id: '/chart-of-accounts',
  path: '/chart-of-accounts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillsRouteRoute = AppBillsRouteRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBankingsRouteRoute = AppBankingsRouteRouteImport.update({
  id: '/bankings',
  path: '/bankings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSuppliersRouteRoute,
} as any)
const AppReceiptsIndexRoute = AppReceiptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReceiptsRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlansRouteRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPaymentsRouteRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMembersRouteRoute,
} as any)
const AppFinancialYearsIndexRoute = AppFinancialYearsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinancialYearsRouteRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExpensesRouteRoute,
} as any)
const AppCommunicationIndexRoute = AppCommunicationIndexRouteImport.update({
  id: '/communication/',
  path: '/communication/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChartOfAccountsIndexRoute = AppChartOfAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChartOfAccountsRouteRoute,
} as any)
const AppBillsIndexRoute = AppBillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBillsRouteRoute,
} as any)
const AppAttendancesIndexRoute = AppAttendancesIndexRouteImport.update({
  id: '/attendances/',
  path: '/attendances/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityLogsIndexRoute = AppActivityLogsIndexRouteImport.update({
  id: '/activity-logs/',
  path: '/activity-logs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiMockApiIndexRoute = ApiMockApiIndexRouteImport.update({
  id: '/api/mock-api/',
  path: '/api/mock-api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestIndexRoute = ApiInngestIndexRouteImport.update({
  id: '/api/inngest/',
  path: '/api/inngest/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersNewRoute = AppUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppSuppliersNewRoute = AppSuppliersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSuppliersRouteRoute,
} as any)
const AppReceiptsNewRoute = AppReceiptsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReceiptsRouteRoute,
} as any)
const AppPlansNewRoute = AppPlansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPlansRouteRoute,
} as any)
const AppPaymentsNewRoute = AppPaymentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPaymentsRouteRoute,
} as any)
const AppMembersNewRoute = AppMembersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppMembersRouteRoute,
} as any)
const AppFinancialYearsNewRoute = AppFinancialYearsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppFinancialYearsRouteRoute,
} as any)
const AppExpensesNewRoute = AppExpensesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppExpensesRouteRoute,
} as any)
const AppChartOfAccountsNewRoute = AppChartOfAccountsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppChartOfAccountsRouteRoute,
} as any)
const AppBillsNewRoute = AppBillsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppBillsRouteRoute,
} as any)
const AppBankingsReconcilliationRoute =
  AppBankingsReconcilliationRouteImport.update({
    id: '/reconcilliation',
    path: '/reconcilliation',
    getParentRoute: () => AppBankingsRouteRoute,
  } as any)
const AppBankingsClearRoute = AppBankingsClearRouteImport.update({
  id: '/clear',
  path: '/clear',
  getParentRoute: () => AppBankingsRouteRoute,
} as any)
const ApiUploadsExpenseAttachmentRoute =
  ApiUploadsExpenseAttachmentRouteImport.update({
    id: '/api/uploads/expense-attachment',
    path: '/api/uploads/expense-attachment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommunicationsGetMembersRoute =
  ApiCommunicationsGetMembersRouteImport.update({
    id: '/api/communications/get-members',
    path: '/api/communications/get-members',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRolesRouteRoute = AppUsersRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppReportsFinanceRouteRoute = AppReportsFinanceRouteRouteImport.update({
  id: '/reports/finance',
  path: '/reports/finance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpensesExpenseIdRouteRoute =
  AppExpensesExpenseIdRouteRouteImport.update({
    id: '/$expenseId',
    path: '/$expenseId',
    getParentRoute: () => AppExpensesRouteRoute,
  } as any)
const AppBankingsPostingsRouteRoute =
  AppBankingsPostingsRouteRouteImport.update({
    id: '/postings',
    path: '/postings',
    getParentRoute: () => AppBankingsRouteRoute,
  } as any)
const AppUsersRolesIndexRoute = AppUsersRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRolesRouteRoute,
} as any)
const AppReportsFinanceIndexRoute = AppReportsFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsFinanceRouteRoute,
} as any)
const AppBankingsPostingsIndexRoute =
  AppBankingsPostingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppBankingsPostingsRouteRoute,
  } as any)
const ApiCronDailyIndexRoute = ApiCronDailyIndexRouteImport.update({
  id: '/api/cron/daily/',
  path: '/api/cron/daily/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRolesNewRoute = AppUsersRolesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppUsersRolesRouteRoute,
} as any)
const AppUsersUserIdResetRoute = AppUsersUserIdResetRouteImport.update({
  id: '/$userId/reset',
  path: '/$userId/reset',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppUsersUserIdEditRoute = AppUsersUserIdEditRouteImport.update({
  id: '/$userId/edit',
  path: '/$userId/edit',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppSuppliersSupplierIdEditRoute =
  AppSuppliersSupplierIdEditRouteImport.update({
    id: '/$supplierId/edit',
    path: '/$supplierId/edit',
    getParentRoute: () => AppSuppliersRouteRoute,
  } as any)
const AppReceiptsReceiptIdDetailsRoute =
  AppReceiptsReceiptIdDetailsRouteImport.update({
    id: '/$receiptId/details',
    path: '/$receiptId/details',
    getParentRoute: () => AppReceiptsRouteRoute,
  } as any)
const AppPlansPlanIdViewMembersRoute =
  AppPlansPlanIdViewMembersRouteImport.update({
    id: '/$planId/view-members',
    path: '/$planId/view-members',
    getParentRoute: () => AppPlansRouteRoute,
  } as any)
const AppPlansPlanIdRevenueRoute = AppPlansPlanIdRevenueRouteImport.update({
  id: '/$planId/revenue',
  path: '/$planId/revenue',
  getParentRoute: () => AppPlansRouteRoute,
} as any)
const AppPlansPlanIdEditRoute = AppPlansPlanIdEditRouteImport.update({
  id: '/$planId/edit',
  path: '/$planId/edit',
  getParentRoute: () => AppPlansRouteRoute,
} as any)
const AppPaymentsPaymentIdEditRoute =
  AppPaymentsPaymentIdEditRouteImport.update({
    id: '/$paymentId/edit',
    path: '/$paymentId/edit',
    getParentRoute: () => AppPaymentsRouteRoute,
  } as any)
const AppPaymentsPaymentIdDetailsRoute =
  AppPaymentsPaymentIdDetailsRouteImport.update({
    id: '/$paymentId/details',
    path: '/$paymentId/details',
    getParentRoute: () => AppPaymentsRouteRoute,
  } as any)
const AppMembersMemberIdProfileRoute =
  AppMembersMemberIdProfileRouteImport.update({
    id: '/$memberId/profile',
    path: '/$memberId/profile',
    getParentRoute: () => AppMembersRouteRoute,
  } as any)
const AppMembersMemberIdEditRoute = AppMembersMemberIdEditRouteImport.update({
  id: '/$memberId/edit',
  path: '/$memberId/edit',
  getParentRoute: () => AppMembersRouteRoute,
} as any)
const AppFinancialYearsFinancialYearIdEditRoute =
  AppFinancialYearsFinancialYearIdEditRouteImport.update({
    id: '/$financialYearId/edit',
    path: '/$financialYearId/edit',
    getParentRoute: () => AppFinancialYearsRouteRoute,
  } as any)
const AppExpensesExpenseIdViewRoute =
  AppExpensesExpenseIdViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => AppExpensesExpenseIdRouteRoute,
  } as any)
const AppExpensesExpenseIdEditRoute =
  AppExpensesExpenseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppExpensesExpenseIdRouteRoute,
  } as any)
const AppChartOfAccountsAccountIdEditRoute =
  AppChartOfAccountsAccountIdEditRouteImport.update({
    id: '/$accountId/edit',
    path: '/$accountId/edit',
    getParentRoute: () => AppChartOfAccountsRouteRoute,
  } as any)
const AppBillsBillIdEditRoute = AppBillsBillIdEditRouteImport.update({
  id: '/$billId/edit',
  path: '/$billId/edit',
  getParentRoute: () => AppBillsRouteRoute,
} as any)
const AppBankingsPostingsNewRoute = AppBankingsPostingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppBankingsPostingsRouteRoute,
} as any)
const AppReportsFinanceTrialBalanceIndexRoute =
  AppReportsFinanceTrialBalanceIndexRouteImport.update({
    id: '/trial-balance/',
    path: '/trial-balance/',
    getParentRoute: () => AppReportsFinanceRouteRoute,
  } as any)
const AppReportsFinanceReceiptsIndexRoute =
  AppReportsFinanceReceiptsIndexRouteImport.update({
    id: '/receipts/',
    path: '/receipts/',
    getParentRoute: () => AppReportsFinanceRouteRoute,
  } as any)
const AppReportsFinancePaymentsIndexRoute =
  AppReportsFinancePaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AppReportsFinanceRouteRoute,
  } as any)
const AppReportsFinanceInvoicesIndexRoute =
  AppReportsFinanceInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AppReportsFinanceRouteRoute,
  } as any)
const AppReportsFinanceIncomeStatementIndexRoute =
  AppReportsFinanceIncomeStatementIndexRouteImport.update({
    id: '/income-statement/',
    path: '/income-statement/',
    getParentRoute: () => AppReportsFinanceRouteRoute,
  } as any)
const AppReportsFinanceExpensesIndexRoute =
  AppReportsFinanceExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AppReportsFinanceRouteRoute,
  } as any)
const AppReportsFinanceBankingIndexRoute =
  AppReportsFinanceBankingIndexRouteImport.update({
    id: '/banking/',
    path: '/banking/',
    getParentRoute: () => AppReportsFinanceRouteRoute,
  } as any)
const AppUsersRolesRoleIdEditRoute = AppUsersRolesRoleIdEditRouteImport.update({
  id: '/$roleId/edit',
  path: '/$roleId/edit',
  getParentRoute: () => AppUsersRolesRouteRoute,
} as any)
const AppBankingsPostingsPostingIdEditRoute =
  AppBankingsPostingsPostingIdEditRouteImport.update({
    id: '/$postingId/edit',
    path: '/$postingId/edit',
    getParentRoute: () => AppBankingsPostingsRouteRoute,
  } as any)
const ApiPaymentsPabfcStkCallbackRoute =
  ApiPaymentsPabfcStkCallbackRouteImport.update({
    id: '/api/payments/pabfc/stk/callback',
    path: '/api/payments/pabfc/stk/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPabfcC2bValidateRoute =
  ApiPaymentsPabfcC2bValidateRouteImport.update({
    id: '/api/payments/pabfc/c2b/validate',
    path: '/api/payments/pabfc/c2b/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPabfcC2bConfRoute = ApiPaymentsPabfcC2bConfRouteImport.update({
  id: '/api/payments/pabfc/c2b/conf',
  path: '/api/payments/pabfc/c2b/conf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/app/bankings': typeof AppBankingsRouteRouteWithChildren
  '/app/bills': typeof AppBillsRouteRouteWithChildren
  '/app/chart-of-accounts': typeof AppChartOfAccountsRouteRouteWithChildren
  '/app/expenses': typeof AppExpensesRouteRouteWithChildren
  '/app/financial-years': typeof AppFinancialYearsRouteRouteWithChildren
  '/app/members': typeof AppMembersRouteRouteWithChildren
  '/app/payments': typeof AppPaymentsRouteRouteWithChildren
  '/app/plans': typeof AppPlansRouteRouteWithChildren
  '/app/receipts': typeof AppReceiptsRouteRouteWithChildren
  '/app/suppliers': typeof AppSuppliersRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal-entries': typeof AppJournalEntriesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/login': typeof MemberLoginRoute
  '/app/bankings/postings': typeof AppBankingsPostingsRouteRouteWithChildren
  '/app/expenses/$expenseId': typeof AppExpensesExpenseIdRouteRouteWithChildren
  '/app/reports/finance': typeof AppReportsFinanceRouteRouteWithChildren
  '/app/users/roles': typeof AppUsersRolesRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/communications/get-members': typeof ApiCommunicationsGetMembersRoute
  '/api/uploads/expense-attachment': typeof ApiUploadsExpenseAttachmentRoute
  '/app/bankings/clear': typeof AppBankingsClearRoute
  '/app/bankings/reconcilliation': typeof AppBankingsReconcilliationRoute
  '/app/bills/new': typeof AppBillsNewRoute
  '/app/chart-of-accounts/new': typeof AppChartOfAccountsNewRoute
  '/app/expenses/new': typeof AppExpensesNewRoute
  '/app/financial-years/new': typeof AppFinancialYearsNewRoute
  '/app/members/new': typeof AppMembersNewRoute
  '/app/payments/new': typeof AppPaymentsNewRoute
  '/app/plans/new': typeof AppPlansNewRoute
  '/app/receipts/new': typeof AppReceiptsNewRoute
  '/app/suppliers/new': typeof AppSuppliersNewRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/api/inngest': typeof ApiInngestIndexRoute
  '/api/mock-api': typeof ApiMockApiIndexRoute
  '/app/activity-logs': typeof AppActivityLogsIndexRoute
  '/app/attendances': typeof AppAttendancesIndexRoute
  '/app/bills/': typeof AppBillsIndexRoute
  '/app/chart-of-accounts/': typeof AppChartOfAccountsIndexRoute
  '/app/communication': typeof AppCommunicationIndexRoute
  '/app/expenses/': typeof AppExpensesIndexRoute
  '/app/financial-years/': typeof AppFinancialYearsIndexRoute
  '/app/members/': typeof AppMembersIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/plans/': typeof AppPlansIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/receipts/': typeof AppReceiptsIndexRoute
  '/app/suppliers/': typeof AppSuppliersIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/bankings/postings/new': typeof AppBankingsPostingsNewRoute
  '/app/bills/$billId/edit': typeof AppBillsBillIdEditRoute
  '/app/chart-of-accounts/$accountId/edit': typeof AppChartOfAccountsAccountIdEditRoute
  '/app/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/app/expenses/$expenseId/view': typeof AppExpensesExpenseIdViewRoute
  '/app/financial-years/$financialYearId/edit': typeof AppFinancialYearsFinancialYearIdEditRoute
  '/app/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/app/members/$memberId/profile': typeof AppMembersMemberIdProfileRoute
  '/app/payments/$paymentId/details': typeof AppPaymentsPaymentIdDetailsRoute
  '/app/payments/$paymentId/edit': typeof AppPaymentsPaymentIdEditRoute
  '/app/plans/$planId/edit': typeof AppPlansPlanIdEditRoute
  '/app/plans/$planId/revenue': typeof AppPlansPlanIdRevenueRoute
  '/app/plans/$planId/view-members': typeof AppPlansPlanIdViewMembersRoute
  '/app/receipts/$receiptId/details': typeof AppReceiptsReceiptIdDetailsRoute
  '/app/suppliers/$supplierId/edit': typeof AppSuppliersSupplierIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/users/$userId/reset': typeof AppUsersUserIdResetRoute
  '/app/users/roles/new': typeof AppUsersRolesNewRoute
  '/api/cron/daily': typeof ApiCronDailyIndexRoute
  '/app/bankings/postings/': typeof AppBankingsPostingsIndexRoute
  '/app/reports/finance/': typeof AppReportsFinanceIndexRoute
  '/app/users/roles/': typeof AppUsersRolesIndexRoute
  '/api/payments/pabfc/c2b/conf': typeof ApiPaymentsPabfcC2bConfRoute
  '/api/payments/pabfc/c2b/validate': typeof ApiPaymentsPabfcC2bValidateRoute
  '/api/payments/pabfc/stk/callback': typeof ApiPaymentsPabfcStkCallbackRoute
  '/app/bankings/postings/$postingId/edit': typeof AppBankingsPostingsPostingIdEditRoute
  '/app/users/roles/$roleId/edit': typeof AppUsersRolesRoleIdEditRoute
  '/app/reports/finance/banking': typeof AppReportsFinanceBankingIndexRoute
  '/app/reports/finance/expenses': typeof AppReportsFinanceExpensesIndexRoute
  '/app/reports/finance/income-statement': typeof AppReportsFinanceIncomeStatementIndexRoute
  '/app/reports/finance/invoices': typeof AppReportsFinanceInvoicesIndexRoute
  '/app/reports/finance/payments': typeof AppReportsFinancePaymentsIndexRoute
  '/app/reports/finance/receipts': typeof AppReportsFinanceReceiptsIndexRoute
  '/app/reports/finance/trial-balance': typeof AppReportsFinanceTrialBalanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/app/bankings': typeof AppBankingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal-entries': typeof AppJournalEntriesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/login': typeof MemberLoginRoute
  '/app/expenses/$expenseId': typeof AppExpensesExpenseIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/communications/get-members': typeof ApiCommunicationsGetMembersRoute
  '/api/uploads/expense-attachment': typeof ApiUploadsExpenseAttachmentRoute
  '/app/bankings/clear': typeof AppBankingsClearRoute
  '/app/bankings/reconcilliation': typeof AppBankingsReconcilliationRoute
  '/app/bills/new': typeof AppBillsNewRoute
  '/app/chart-of-accounts/new': typeof AppChartOfAccountsNewRoute
  '/app/expenses/new': typeof AppExpensesNewRoute
  '/app/financial-years/new': typeof AppFinancialYearsNewRoute
  '/app/members/new': typeof AppMembersNewRoute
  '/app/payments/new': typeof AppPaymentsNewRoute
  '/app/plans/new': typeof AppPlansNewRoute
  '/app/receipts/new': typeof AppReceiptsNewRoute
  '/app/suppliers/new': typeof AppSuppliersNewRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/api/inngest': typeof ApiInngestIndexRoute
  '/api/mock-api': typeof ApiMockApiIndexRoute
  '/app/activity-logs': typeof AppActivityLogsIndexRoute
  '/app/attendances': typeof AppAttendancesIndexRoute
  '/app/bills': typeof AppBillsIndexRoute
  '/app/chart-of-accounts': typeof AppChartOfAccountsIndexRoute
  '/app/communication': typeof AppCommunicationIndexRoute
  '/app/expenses': typeof AppExpensesIndexRoute
  '/app/financial-years': typeof AppFinancialYearsIndexRoute
  '/app/members': typeof AppMembersIndexRoute
  '/app/payments': typeof AppPaymentsIndexRoute
  '/app/plans': typeof AppPlansIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/receipts': typeof AppReceiptsIndexRoute
  '/app/suppliers': typeof AppSuppliersIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/bankings/postings/new': typeof AppBankingsPostingsNewRoute
  '/app/bills/$billId/edit': typeof AppBillsBillIdEditRoute
  '/app/chart-of-accounts/$accountId/edit': typeof AppChartOfAccountsAccountIdEditRoute
  '/app/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/app/expenses/$expenseId/view': typeof AppExpensesExpenseIdViewRoute
  '/app/financial-years/$financialYearId/edit': typeof AppFinancialYearsFinancialYearIdEditRoute
  '/app/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/app/members/$memberId/profile': typeof AppMembersMemberIdProfileRoute
  '/app/payments/$paymentId/details': typeof AppPaymentsPaymentIdDetailsRoute
  '/app/payments/$paymentId/edit': typeof AppPaymentsPaymentIdEditRoute
  '/app/plans/$planId/edit': typeof AppPlansPlanIdEditRoute
  '/app/plans/$planId/revenue': typeof AppPlansPlanIdRevenueRoute
  '/app/plans/$planId/view-members': typeof AppPlansPlanIdViewMembersRoute
  '/app/receipts/$receiptId/details': typeof AppReceiptsReceiptIdDetailsRoute
  '/app/suppliers/$supplierId/edit': typeof AppSuppliersSupplierIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/users/$userId/reset': typeof AppUsersUserIdResetRoute
  '/app/users/roles/new': typeof AppUsersRolesNewRoute
  '/api/cron/daily': typeof ApiCronDailyIndexRoute
  '/app/bankings/postings': typeof AppBankingsPostingsIndexRoute
  '/app/reports/finance': typeof AppReportsFinanceIndexRoute
  '/app/users/roles': typeof AppUsersRolesIndexRoute
  '/api/payments/pabfc/c2b/conf': typeof ApiPaymentsPabfcC2bConfRoute
  '/api/payments/pabfc/c2b/validate': typeof ApiPaymentsPabfcC2bValidateRoute
  '/api/payments/pabfc/stk/callback': typeof ApiPaymentsPabfcStkCallbackRoute
  '/app/bankings/postings/$postingId/edit': typeof AppBankingsPostingsPostingIdEditRoute
  '/app/users/roles/$roleId/edit': typeof AppUsersRolesRoleIdEditRoute
  '/app/reports/finance/banking': typeof AppReportsFinanceBankingIndexRoute
  '/app/reports/finance/expenses': typeof AppReportsFinanceExpensesIndexRoute
  '/app/reports/finance/income-statement': typeof AppReportsFinanceIncomeStatementIndexRoute
  '/app/reports/finance/invoices': typeof AppReportsFinanceInvoicesIndexRoute
  '/app/reports/finance/payments': typeof AppReportsFinancePaymentsIndexRoute
  '/app/reports/finance/receipts': typeof AppReportsFinanceReceiptsIndexRoute
  '/app/reports/finance/trial-balance': typeof AppReportsFinanceTrialBalanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/app/bankings': typeof AppBankingsRouteRouteWithChildren
  '/app/bills': typeof AppBillsRouteRouteWithChildren
  '/app/chart-of-accounts': typeof AppChartOfAccountsRouteRouteWithChildren
  '/app/expenses': typeof AppExpensesRouteRouteWithChildren
  '/app/financial-years': typeof AppFinancialYearsRouteRouteWithChildren
  '/app/members': typeof AppMembersRouteRouteWithChildren
  '/app/payments': typeof AppPaymentsRouteRouteWithChildren
  '/app/plans': typeof AppPlansRouteRouteWithChildren
  '/app/receipts': typeof AppReceiptsRouteRouteWithChildren
  '/app/suppliers': typeof AppSuppliersRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal-entries': typeof AppJournalEntriesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/login': typeof MemberLoginRoute
  '/app/bankings/postings': typeof AppBankingsPostingsRouteRouteWithChildren
  '/app/expenses/$expenseId': typeof AppExpensesExpenseIdRouteRouteWithChildren
  '/app/reports/finance': typeof AppReportsFinanceRouteRouteWithChildren
  '/app/users/roles': typeof AppUsersRolesRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/communications/get-members': typeof ApiCommunicationsGetMembersRoute
  '/api/uploads/expense-attachment': typeof ApiUploadsExpenseAttachmentRoute
  '/app/bankings/clear': typeof AppBankingsClearRoute
  '/app/bankings/reconcilliation': typeof AppBankingsReconcilliationRoute
  '/app/bills/new': typeof AppBillsNewRoute
  '/app/chart-of-accounts/new': typeof AppChartOfAccountsNewRoute
  '/app/expenses/new': typeof AppExpensesNewRoute
  '/app/financial-years/new': typeof AppFinancialYearsNewRoute
  '/app/members/new': typeof AppMembersNewRoute
  '/app/payments/new': typeof AppPaymentsNewRoute
  '/app/plans/new': typeof AppPlansNewRoute
  '/app/receipts/new': typeof AppReceiptsNewRoute
  '/app/suppliers/new': typeof AppSuppliersNewRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/api/inngest/': typeof ApiInngestIndexRoute
  '/api/mock-api/': typeof ApiMockApiIndexRoute
  '/app/activity-logs/': typeof AppActivityLogsIndexRoute
  '/app/attendances/': typeof AppAttendancesIndexRoute
  '/app/bills/': typeof AppBillsIndexRoute
  '/app/chart-of-accounts/': typeof AppChartOfAccountsIndexRoute
  '/app/communication/': typeof AppCommunicationIndexRoute
  '/app/expenses/': typeof AppExpensesIndexRoute
  '/app/financial-years/': typeof AppFinancialYearsIndexRoute
  '/app/members/': typeof AppMembersIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/plans/': typeof AppPlansIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/receipts/': typeof AppReceiptsIndexRoute
  '/app/suppliers/': typeof AppSuppliersIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/bankings/postings/new': typeof AppBankingsPostingsNewRoute
  '/app/bills/$billId/edit': typeof AppBillsBillIdEditRoute
  '/app/chart-of-accounts/$accountId/edit': typeof AppChartOfAccountsAccountIdEditRoute
  '/app/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/app/expenses/$expenseId/view': typeof AppExpensesExpenseIdViewRoute
  '/app/financial-years/$financialYearId/edit': typeof AppFinancialYearsFinancialYearIdEditRoute
  '/app/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/app/members/$memberId/profile': typeof AppMembersMemberIdProfileRoute
  '/app/payments/$paymentId/details': typeof AppPaymentsPaymentIdDetailsRoute
  '/app/payments/$paymentId/edit': typeof AppPaymentsPaymentIdEditRoute
  '/app/plans/$planId/edit': typeof AppPlansPlanIdEditRoute
  '/app/plans/$planId/revenue': typeof AppPlansPlanIdRevenueRoute
  '/app/plans/$planId/view-members': typeof AppPlansPlanIdViewMembersRoute
  '/app/receipts/$receiptId/details': typeof AppReceiptsReceiptIdDetailsRoute
  '/app/suppliers/$supplierId/edit': typeof AppSuppliersSupplierIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/users/$userId/reset': typeof AppUsersUserIdResetRoute
  '/app/users/roles/new': typeof AppUsersRolesNewRoute
  '/api/cron/daily/': typeof ApiCronDailyIndexRoute
  '/app/bankings/postings/': typeof AppBankingsPostingsIndexRoute
  '/app/reports/finance/': typeof AppReportsFinanceIndexRoute
  '/app/users/roles/': typeof AppUsersRolesIndexRoute
  '/api/payments/pabfc/c2b/conf': typeof ApiPaymentsPabfcC2bConfRoute
  '/api/payments/pabfc/c2b/validate': typeof ApiPaymentsPabfcC2bValidateRoute
  '/api/payments/pabfc/stk/callback': typeof ApiPaymentsPabfcStkCallbackRoute
  '/app/bankings/postings/$postingId/edit': typeof AppBankingsPostingsPostingIdEditRoute
  '/app/users/roles/$roleId/edit': typeof AppUsersRolesRoleIdEditRoute
  '/app/reports/finance/banking/': typeof AppReportsFinanceBankingIndexRoute
  '/app/reports/finance/expenses/': typeof AppReportsFinanceExpensesIndexRoute
  '/app/reports/finance/income-statement/': typeof AppReportsFinanceIncomeStatementIndexRoute
  '/app/reports/finance/invoices/': typeof AppReportsFinanceInvoicesIndexRoute
  '/app/reports/finance/payments/': typeof AppReportsFinancePaymentsIndexRoute
  '/app/reports/finance/receipts/': typeof AppReportsFinanceReceiptsIndexRoute
  '/app/reports/finance/trial-balance/': typeof AppReportsFinanceTrialBalanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/member'
    | '/app/bankings'
    | '/app/bills'
    | '/app/chart-of-accounts'
    | '/app/expenses'
    | '/app/financial-years'
    | '/app/members'
    | '/app/payments'
    | '/app/plans'
    | '/app/receipts'
    | '/app/suppliers'
    | '/app/users'
    | '/forgot-password'
    | '/sign-in'
    | '/app/dashboard'
    | '/app/journal-entries'
    | '/app/settings'
    | '/app/unauthorized'
    | '/member/dashboard'
    | '/member/login'
    | '/app/bankings/postings'
    | '/app/expenses/$expenseId'
    | '/app/reports/finance'
    | '/app/users/roles'
    | '/api/auth/$'
    | '/api/communications/get-members'
    | '/api/uploads/expense-attachment'
    | '/app/bankings/clear'
    | '/app/bankings/reconcilliation'
    | '/app/bills/new'
    | '/app/chart-of-accounts/new'
    | '/app/expenses/new'
    | '/app/financial-years/new'
    | '/app/members/new'
    | '/app/payments/new'
    | '/app/plans/new'
    | '/app/receipts/new'
    | '/app/suppliers/new'
    | '/app/users/new'
    | '/api/inngest'
    | '/api/mock-api'
    | '/app/activity-logs'
    | '/app/attendances'
    | '/app/bills/'
    | '/app/chart-of-accounts/'
    | '/app/communication'
    | '/app/expenses/'
    | '/app/financial-years/'
    | '/app/members/'
    | '/app/payments/'
    | '/app/plans/'
    | '/app/profile'
    | '/app/receipts/'
    | '/app/suppliers/'
    | '/app/users/'
    | '/app/bankings/postings/new'
    | '/app/bills/$billId/edit'
    | '/app/chart-of-accounts/$accountId/edit'
    | '/app/expenses/$expenseId/edit'
    | '/app/expenses/$expenseId/view'
    | '/app/financial-years/$financialYearId/edit'
    | '/app/members/$memberId/edit'
    | '/app/members/$memberId/profile'
    | '/app/payments/$paymentId/details'
    | '/app/payments/$paymentId/edit'
    | '/app/plans/$planId/edit'
    | '/app/plans/$planId/revenue'
    | '/app/plans/$planId/view-members'
    | '/app/receipts/$receiptId/details'
    | '/app/suppliers/$supplierId/edit'
    | '/app/users/$userId/edit'
    | '/app/users/$userId/reset'
    | '/app/users/roles/new'
    | '/api/cron/daily'
    | '/app/bankings/postings/'
    | '/app/reports/finance/'
    | '/app/users/roles/'
    | '/api/payments/pabfc/c2b/conf'
    | '/api/payments/pabfc/c2b/validate'
    | '/api/payments/pabfc/stk/callback'
    | '/app/bankings/postings/$postingId/edit'
    | '/app/users/roles/$roleId/edit'
    | '/app/reports/finance/banking'
    | '/app/reports/finance/expenses'
    | '/app/reports/finance/income-statement'
    | '/app/reports/finance/invoices'
    | '/app/reports/finance/payments'
    | '/app/reports/finance/receipts'
    | '/app/reports/finance/trial-balance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/member'
    | '/app/bankings'
    | '/forgot-password'
    | '/sign-in'
    | '/app/dashboard'
    | '/app/journal-entries'
    | '/app/settings'
    | '/app/unauthorized'
    | '/member/dashboard'
    | '/member/login'
    | '/app/expenses/$expenseId'
    | '/api/auth/$'
    | '/api/communications/get-members'
    | '/api/uploads/expense-attachment'
    | '/app/bankings/clear'
    | '/app/bankings/reconcilliation'
    | '/app/bills/new'
    | '/app/chart-of-accounts/new'
    | '/app/expenses/new'
    | '/app/financial-years/new'
    | '/app/members/new'
    | '/app/payments/new'
    | '/app/plans/new'
    | '/app/receipts/new'
    | '/app/suppliers/new'
    | '/app/users/new'
    | '/api/inngest'
    | '/api/mock-api'
    | '/app/activity-logs'
    | '/app/attendances'
    | '/app/bills'
    | '/app/chart-of-accounts'
    | '/app/communication'
    | '/app/expenses'
    | '/app/financial-years'
    | '/app/members'
    | '/app/payments'
    | '/app/plans'
    | '/app/profile'
    | '/app/receipts'
    | '/app/suppliers'
    | '/app/users'
    | '/app/bankings/postings/new'
    | '/app/bills/$billId/edit'
    | '/app/chart-of-accounts/$accountId/edit'
    | '/app/expenses/$expenseId/edit'
    | '/app/expenses/$expenseId/view'
    | '/app/financial-years/$financialYearId/edit'
    | '/app/members/$memberId/edit'
    | '/app/members/$memberId/profile'
    | '/app/payments/$paymentId/details'
    | '/app/payments/$paymentId/edit'
    | '/app/plans/$planId/edit'
    | '/app/plans/$planId/revenue'
    | '/app/plans/$planId/view-members'
    | '/app/receipts/$receiptId/details'
    | '/app/suppliers/$supplierId/edit'
    | '/app/users/$userId/edit'
    | '/app/users/$userId/reset'
    | '/app/users/roles/new'
    | '/api/cron/daily'
    | '/app/bankings/postings'
    | '/app/reports/finance'
    | '/app/users/roles'
    | '/api/payments/pabfc/c2b/conf'
    | '/api/payments/pabfc/c2b/validate'
    | '/api/payments/pabfc/stk/callback'
    | '/app/bankings/postings/$postingId/edit'
    | '/app/users/roles/$roleId/edit'
    | '/app/reports/finance/banking'
    | '/app/reports/finance/expenses'
    | '/app/reports/finance/income-statement'
    | '/app/reports/finance/invoices'
    | '/app/reports/finance/payments'
    | '/app/reports/finance/receipts'
    | '/app/reports/finance/trial-balance'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/app'
    | '/member'
    | '/app/bankings'
    | '/app/bills'
    | '/app/chart-of-accounts'
    | '/app/expenses'
    | '/app/financial-years'
    | '/app/members'
    | '/app/payments'
    | '/app/plans'
    | '/app/receipts'
    | '/app/suppliers'
    | '/app/users'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/app/dashboard'
    | '/app/journal-entries'
    | '/app/settings'
    | '/app/unauthorized'
    | '/member/dashboard'
    | '/member/login'
    | '/app/bankings/postings'
    | '/app/expenses/$expenseId'
    | '/app/reports/finance'
    | '/app/users/roles'
    | '/api/auth/$'
    | '/api/communications/get-members'
    | '/api/uploads/expense-attachment'
    | '/app/bankings/clear'
    | '/app/bankings/reconcilliation'
    | '/app/bills/new'
    | '/app/chart-of-accounts/new'
    | '/app/expenses/new'
    | '/app/financial-years/new'
    | '/app/members/new'
    | '/app/payments/new'
    | '/app/plans/new'
    | '/app/receipts/new'
    | '/app/suppliers/new'
    | '/app/users/new'
    | '/api/inngest/'
    | '/api/mock-api/'
    | '/app/activity-logs/'
    | '/app/attendances/'
    | '/app/bills/'
    | '/app/chart-of-accounts/'
    | '/app/communication/'
    | '/app/expenses/'
    | '/app/financial-years/'
    | '/app/members/'
    | '/app/payments/'
    | '/app/plans/'
    | '/app/profile/'
    | '/app/receipts/'
    | '/app/suppliers/'
    | '/app/users/'
    | '/app/bankings/postings/new'
    | '/app/bills/$billId/edit'
    | '/app/chart-of-accounts/$accountId/edit'
    | '/app/expenses/$expenseId/edit'
    | '/app/expenses/$expenseId/view'
    | '/app/financial-years/$financialYearId/edit'
    | '/app/members/$memberId/edit'
    | '/app/members/$memberId/profile'
    | '/app/payments/$paymentId/details'
    | '/app/payments/$paymentId/edit'
    | '/app/plans/$planId/edit'
    | '/app/plans/$planId/revenue'
    | '/app/plans/$planId/view-members'
    | '/app/receipts/$receiptId/details'
    | '/app/suppliers/$supplierId/edit'
    | '/app/users/$userId/edit'
    | '/app/users/$userId/reset'
    | '/app/users/roles/new'
    | '/api/cron/daily/'
    | '/app/bankings/postings/'
    | '/app/reports/finance/'
    | '/app/users/roles/'
    | '/api/payments/pabfc/c2b/conf'
    | '/api/payments/pabfc/c2b/validate'
    | '/api/payments/pabfc/stk/callback'
    | '/app/bankings/postings/$postingId/edit'
    | '/app/users/roles/$roleId/edit'
    | '/app/reports/finance/banking/'
    | '/app/reports/finance/expenses/'
    | '/app/reports/finance/income-statement/'
    | '/app/reports/finance/invoices/'
    | '/app/reports/finance/payments/'
    | '/app/reports/finance/receipts/'
    | '/app/reports/finance/trial-balance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  MemberRouteRoute: typeof MemberRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCommunicationsGetMembersRoute: typeof ApiCommunicationsGetMembersRoute
  ApiUploadsExpenseAttachmentRoute: typeof ApiUploadsExpenseAttachmentRoute
  ApiInngestIndexRoute: typeof ApiInngestIndexRoute
  ApiMockApiIndexRoute: typeof ApiMockApiIndexRoute
  ApiCronDailyIndexRoute: typeof ApiCronDailyIndexRoute
  ApiPaymentsPabfcC2bConfRoute: typeof ApiPaymentsPabfcC2bConfRoute
  ApiPaymentsPabfcC2bValidateRoute: typeof ApiPaymentsPabfcC2bValidateRoute
  ApiPaymentsPabfcStkCallbackRoute: typeof ApiPaymentsPabfcStkCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/login': {
      id: '/member/login'
      path: '/login'
      fullPath: '/member/login'
      preLoaderRoute: typeof MemberLoginRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/dashboard': {
      id: '/member/dashboard'
      path: '/dashboard'
      fullPath: '/member/dashboard'
      preLoaderRoute: typeof MemberDashboardRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/app/unauthorized': {
      id: '/app/unauthorized'
      path: '/unauthorized'
      fullPath: '/app/unauthorized'
      preLoaderRoute: typeof AppUnauthorizedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/journal-entries': {
      id: '/app/journal-entries'
      path: '/journal-entries'
      fullPath: '/app/journal-entries'
      preLoaderRoute: typeof AppJournalEntriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/receipts': {
      id: '/app/receipts'
      path: '/receipts'
      fullPath: '/app/receipts'
      preLoaderRoute: typeof AppReceiptsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/financial-years': {
      id: '/app/financial-years'
      path: '/financial-years'
      fullPath: '/app/financial-years'
      preLoaderRoute: typeof AppFinancialYearsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chart-of-accounts': {
      id: '/app/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/app/chart-of-accounts'
      preLoaderRoute: typeof AppChartOfAccountsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/bankings': {
      id: '/app/bankings'
      path: '/bankings'
      fullPath: '/app/bankings'
      preLoaderRoute: typeof AppBankingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/suppliers/': {
      id: '/app/suppliers/'
      path: '/'
      fullPath: '/app/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppSuppliersRouteRoute
    }
    '/app/receipts/': {
      id: '/app/receipts/'
      path: '/'
      fullPath: '/app/receipts/'
      preLoaderRoute: typeof AppReceiptsIndexRouteImport
      parentRoute: typeof AppReceiptsRouteRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/plans/': {
      id: '/app/plans/'
      path: '/'
      fullPath: '/app/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/app/payments/': {
      id: '/app/payments/'
      path: '/'
      fullPath: '/app/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppPaymentsRouteRoute
    }
    '/app/members/': {
      id: '/app/members/'
      path: '/'
      fullPath: '/app/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppMembersRouteRoute
    }
    '/app/financial-years/': {
      id: '/app/financial-years/'
      path: '/'
      fullPath: '/app/financial-years/'
      preLoaderRoute: typeof AppFinancialYearsIndexRouteImport
      parentRoute: typeof AppFinancialYearsRouteRoute
    }
    '/app/expenses/': {
      id: '/app/expenses/'
      path: '/'
      fullPath: '/app/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppExpensesRouteRoute
    }
    '/app/communication/': {
      id: '/app/communication/'
      path: '/communication'
      fullPath: '/app/communication'
      preLoaderRoute: typeof AppCommunicationIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chart-of-accounts/': {
      id: '/app/chart-of-accounts/'
      path: '/'
      fullPath: '/app/chart-of-accounts/'
      preLoaderRoute: typeof AppChartOfAccountsIndexRouteImport
      parentRoute: typeof AppChartOfAccountsRouteRoute
    }
    '/app/bills/': {
      id: '/app/bills/'
      path: '/'
      fullPath: '/app/bills/'
      preLoaderRoute: typeof AppBillsIndexRouteImport
      parentRoute: typeof AppBillsRouteRoute
    }
    '/app/attendances/': {
      id: '/app/attendances/'
      path: '/attendances'
      fullPath: '/app/attendances'
      preLoaderRoute: typeof AppAttendancesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/activity-logs/': {
      id: '/app/activity-logs/'
      path: '/activity-logs'
      fullPath: '/app/activity-logs'
      preLoaderRoute: typeof AppActivityLogsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/mock-api/': {
      id: '/api/mock-api/'
      path: '/api/mock-api'
      fullPath: '/api/mock-api'
      preLoaderRoute: typeof ApiMockApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest/': {
      id: '/api/inngest/'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users/new': {
      id: '/app/users/new'
      path: '/new'
      fullPath: '/app/users/new'
      preLoaderRoute: typeof AppUsersNewRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/suppliers/new': {
      id: '/app/suppliers/new'
      path: '/new'
      fullPath: '/app/suppliers/new'
      preLoaderRoute: typeof AppSuppliersNewRouteImport
      parentRoute: typeof AppSuppliersRouteRoute
    }
    '/app/receipts/new': {
      id: '/app/receipts/new'
      path: '/new'
      fullPath: '/app/receipts/new'
      preLoaderRoute: typeof AppReceiptsNewRouteImport
      parentRoute: typeof AppReceiptsRouteRoute
    }
    '/app/plans/new': {
      id: '/app/plans/new'
      path: '/new'
      fullPath: '/app/plans/new'
      preLoaderRoute: typeof AppPlansNewRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/app/payments/new': {
      id: '/app/payments/new'
      path: '/new'
      fullPath: '/app/payments/new'
      preLoaderRoute: typeof AppPaymentsNewRouteImport
      parentRoute: typeof AppPaymentsRouteRoute
    }
    '/app/members/new': {
      id: '/app/members/new'
      path: '/new'
      fullPath: '/app/members/new'
      preLoaderRoute: typeof AppMembersNewRouteImport
      parentRoute: typeof AppMembersRouteRoute
    }
    '/app/financial-years/new': {
      id: '/app/financial-years/new'
      path: '/new'
      fullPath: '/app/financial-years/new'
      preLoaderRoute: typeof AppFinancialYearsNewRouteImport
      parentRoute: typeof AppFinancialYearsRouteRoute
    }
    '/app/expenses/new': {
      id: '/app/expenses/new'
      path: '/new'
      fullPath: '/app/expenses/new'
      preLoaderRoute: typeof AppExpensesNewRouteImport
      parentRoute: typeof AppExpensesRouteRoute
    }
    '/app/chart-of-accounts/new': {
      id: '/app/chart-of-accounts/new'
      path: '/new'
      fullPath: '/app/chart-of-accounts/new'
      preLoaderRoute: typeof AppChartOfAccountsNewRouteImport
      parentRoute: typeof AppChartOfAccountsRouteRoute
    }
    '/app/bills/new': {
      id: '/app/bills/new'
      path: '/new'
      fullPath: '/app/bills/new'
      preLoaderRoute: typeof AppBillsNewRouteImport
      parentRoute: typeof AppBillsRouteRoute
    }
    '/app/bankings/reconcilliation': {
      id: '/app/bankings/reconcilliation'
      path: '/reconcilliation'
      fullPath: '/app/bankings/reconcilliation'
      preLoaderRoute: typeof AppBankingsReconcilliationRouteImport
      parentRoute: typeof AppBankingsRouteRoute
    }
    '/app/bankings/clear': {
      id: '/app/bankings/clear'
      path: '/clear'
      fullPath: '/app/bankings/clear'
      preLoaderRoute: typeof AppBankingsClearRouteImport
      parentRoute: typeof AppBankingsRouteRoute
    }
    '/api/uploads/expense-attachment': {
      id: '/api/uploads/expense-attachment'
      path: '/api/uploads/expense-attachment'
      fullPath: '/api/uploads/expense-attachment'
      preLoaderRoute: typeof ApiUploadsExpenseAttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communications/get-members': {
      id: '/api/communications/get-members'
      path: '/api/communications/get-members'
      fullPath: '/api/communications/get-members'
      preLoaderRoute: typeof ApiCommunicationsGetMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users/roles': {
      id: '/app/users/roles'
      path: '/roles'
      fullPath: '/app/users/roles'
      preLoaderRoute: typeof AppUsersRolesRouteRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/reports/finance': {
      id: '/app/reports/finance'
      path: '/reports/finance'
      fullPath: '/app/reports/finance'
      preLoaderRoute: typeof AppReportsFinanceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/expenses/$expenseId': {
      id: '/app/expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/app/expenses/$expenseId'
      preLoaderRoute: typeof AppExpensesExpenseIdRouteRouteImport
      parentRoute: typeof AppExpensesRouteRoute
    }
    '/app/bankings/postings': {
      id: '/app/bankings/postings'
      path: '/postings'
      fullPath: '/app/bankings/postings'
      preLoaderRoute: typeof AppBankingsPostingsRouteRouteImport
      parentRoute: typeof AppBankingsRouteRoute
    }
    '/app/users/roles/': {
      id: '/app/users/roles/'
      path: '/'
      fullPath: '/app/users/roles/'
      preLoaderRoute: typeof AppUsersRolesIndexRouteImport
      parentRoute: typeof AppUsersRolesRouteRoute
    }
    '/app/reports/finance/': {
      id: '/app/reports/finance/'
      path: '/'
      fullPath: '/app/reports/finance/'
      preLoaderRoute: typeof AppReportsFinanceIndexRouteImport
      parentRoute: typeof AppReportsFinanceRouteRoute
    }
    '/app/bankings/postings/': {
      id: '/app/bankings/postings/'
      path: '/'
      fullPath: '/app/bankings/postings/'
      preLoaderRoute: typeof AppBankingsPostingsIndexRouteImport
      parentRoute: typeof AppBankingsPostingsRouteRoute
    }
    '/api/cron/daily/': {
      id: '/api/cron/daily/'
      path: '/api/cron/daily'
      fullPath: '/api/cron/daily'
      preLoaderRoute: typeof ApiCronDailyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users/roles/new': {
      id: '/app/users/roles/new'
      path: '/new'
      fullPath: '/app/users/roles/new'
      preLoaderRoute: typeof AppUsersRolesNewRouteImport
      parentRoute: typeof AppUsersRolesRouteRoute
    }
    '/app/users/$userId/reset': {
      id: '/app/users/$userId/reset'
      path: '/$userId/reset'
      fullPath: '/app/users/$userId/reset'
      preLoaderRoute: typeof AppUsersUserIdResetRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/users/$userId/edit': {
      id: '/app/users/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/app/users/$userId/edit'
      preLoaderRoute: typeof AppUsersUserIdEditRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/suppliers/$supplierId/edit': {
      id: '/app/suppliers/$supplierId/edit'
      path: '/$supplierId/edit'
      fullPath: '/app/suppliers/$supplierId/edit'
      preLoaderRoute: typeof AppSuppliersSupplierIdEditRouteImport
      parentRoute: typeof AppSuppliersRouteRoute
    }
    '/app/receipts/$receiptId/details': {
      id: '/app/receipts/$receiptId/details'
      path: '/$receiptId/details'
      fullPath: '/app/receipts/$receiptId/details'
      preLoaderRoute: typeof AppReceiptsReceiptIdDetailsRouteImport
      parentRoute: typeof AppReceiptsRouteRoute
    }
    '/app/plans/$planId/view-members': {
      id: '/app/plans/$planId/view-members'
      path: '/$planId/view-members'
      fullPath: '/app/plans/$planId/view-members'
      preLoaderRoute: typeof AppPlansPlanIdViewMembersRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/app/plans/$planId/revenue': {
      id: '/app/plans/$planId/revenue'
      path: '/$planId/revenue'
      fullPath: '/app/plans/$planId/revenue'
      preLoaderRoute: typeof AppPlansPlanIdRevenueRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/app/plans/$planId/edit': {
      id: '/app/plans/$planId/edit'
      path: '/$planId/edit'
      fullPath: '/app/plans/$planId/edit'
      preLoaderRoute: typeof AppPlansPlanIdEditRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/app/payments/$paymentId/edit': {
      id: '/app/payments/$paymentId/edit'
      path: '/$paymentId/edit'
      fullPath: '/app/payments/$paymentId/edit'
      preLoaderRoute: typeof AppPaymentsPaymentIdEditRouteImport
      parentRoute: typeof AppPaymentsRouteRoute
    }
    '/app/payments/$paymentId/details': {
      id: '/app/payments/$paymentId/details'
      path: '/$paymentId/details'
      fullPath: '/app/payments/$paymentId/details'
      preLoaderRoute: typeof AppPaymentsPaymentIdDetailsRouteImport
      parentRoute: typeof AppPaymentsRouteRoute
    }
    '/app/members/$memberId/profile': {
      id: '/app/members/$memberId/profile'
      path: '/$memberId/profile'
      fullPath: '/app/members/$memberId/profile'
      preLoaderRoute: typeof AppMembersMemberIdProfileRouteImport
      parentRoute: typeof AppMembersRouteRoute
    }
    '/app/members/$memberId/edit': {
      id: '/app/members/$memberId/edit'
      path: '/$memberId/edit'
      fullPath: '/app/members/$memberId/edit'
      preLoaderRoute: typeof AppMembersMemberIdEditRouteImport
      parentRoute: typeof AppMembersRouteRoute
    }
    '/app/financial-years/$financialYearId/edit': {
      id: '/app/financial-years/$financialYearId/edit'
      path: '/$financialYearId/edit'
      fullPath: '/app/financial-years/$financialYearId/edit'
      preLoaderRoute: typeof AppFinancialYearsFinancialYearIdEditRouteImport
      parentRoute: typeof AppFinancialYearsRouteRoute
    }
    '/app/expenses/$expenseId/view': {
      id: '/app/expenses/$expenseId/view'
      path: '/view'
      fullPath: '/app/expenses/$expenseId/view'
      preLoaderRoute: typeof AppExpensesExpenseIdViewRouteImport
      parentRoute: typeof AppExpensesExpenseIdRouteRoute
    }
    '/app/expenses/$expenseId/edit': {
      id: '/app/expenses/$expenseId/edit'
      path: '/edit'
      fullPath: '/app/expenses/$expenseId/edit'
      preLoaderRoute: typeof AppExpensesExpenseIdEditRouteImport
      parentRoute: typeof AppExpensesExpenseIdRouteRoute
    }
    '/app/chart-of-accounts/$accountId/edit': {
      id: '/app/chart-of-accounts/$accountId/edit'
      path: '/$accountId/edit'
      fullPath: '/app/chart-of-accounts/$accountId/edit'
      preLoaderRoute: typeof AppChartOfAccountsAccountIdEditRouteImport
      parentRoute: typeof AppChartOfAccountsRouteRoute
    }
    '/app/bills/$billId/edit': {
      id: '/app/bills/$billId/edit'
      path: '/$billId/edit'
      fullPath: '/app/bills/$billId/edit'
      preLoaderRoute: typeof AppBillsBillIdEditRouteImport
      parentRoute: typeof AppBillsRouteRoute
    }
    '/app/bankings/postings/new': {
      id: '/app/bankings/postings/new'
      path: '/new'
      fullPath: '/app/bankings/postings/new'
      preLoaderRoute: typeof AppBankingsPostingsNewRouteImport
      parentRoute: typeof AppBankingsPostingsRouteRoute
    }
    '/app/reports/finance/trial-balance/': {
      id: '/app/reports/finance/trial-balance/'
      path: '/trial-balance'
      fullPath: '/app/reports/finance/trial-balance'
      preLoaderRoute: typeof AppReportsFinanceTrialBalanceIndexRouteImport
      parentRoute: typeof AppReportsFinanceRouteRoute
    }
    '/app/reports/finance/receipts/': {
      id: '/app/reports/finance/receipts/'
      path: '/receipts'
      fullPath: '/app/reports/finance/receipts'
      preLoaderRoute: typeof AppReportsFinanceReceiptsIndexRouteImport
      parentRoute: typeof AppReportsFinanceRouteRoute
    }
    '/app/reports/finance/payments/': {
      id: '/app/reports/finance/payments/'
      path: '/payments'
      fullPath: '/app/reports/finance/payments'
      preLoaderRoute: typeof AppReportsFinancePaymentsIndexRouteImport
      parentRoute: typeof AppReportsFinanceRouteRoute
    }
    '/app/reports/finance/invoices/': {
      id: '/app/reports/finance/invoices/'
      path: '/invoices'
      fullPath: '/app/reports/finance/invoices'
      preLoaderRoute: typeof AppReportsFinanceInvoicesIndexRouteImport
      parentRoute: typeof AppReportsFinanceRouteRoute
    }
    '/app/reports/finance/income-statement/': {
      id: '/app/reports/finance/income-statement/'
      path: '/income-statement'
      fullPath: '/app/reports/finance/income-statement'
      preLoaderRoute: typeof AppReportsFinanceIncomeStatementIndexRouteImport
      parentRoute: typeof AppReportsFinanceRouteRoute
    }
    '/app/reports/finance/expenses/': {
      id: '/app/reports/finance/expenses/'
      path: '/expenses'
      fullPath: '/app/reports/finance/expenses'
      preLoaderRoute: typeof AppReportsFinanceExpensesIndexRouteImport
      parentRoute: typeof AppReportsFinanceRouteRoute
    }
    '/app/reports/finance/banking/': {
      id: '/app/reports/finance/banking/'
      path: '/banking'
      fullPath: '/app/reports/finance/banking'
      preLoaderRoute: typeof AppReportsFinanceBankingIndexRouteImport
      parentRoute: typeof AppReportsFinanceRouteRoute
    }
    '/app/users/roles/$roleId/edit': {
      id: '/app/users/roles/$roleId/edit'
      path: '/$roleId/edit'
      fullPath: '/app/users/roles/$roleId/edit'
      preLoaderRoute: typeof AppUsersRolesRoleIdEditRouteImport
      parentRoute: typeof AppUsersRolesRouteRoute
    }
    '/app/bankings/postings/$postingId/edit': {
      id: '/app/bankings/postings/$postingId/edit'
      path: '/$postingId/edit'
      fullPath: '/app/bankings/postings/$postingId/edit'
      preLoaderRoute: typeof AppBankingsPostingsPostingIdEditRouteImport
      parentRoute: typeof AppBankingsPostingsRouteRoute
    }
    '/api/payments/pabfc/stk/callback': {
      id: '/api/payments/pabfc/stk/callback'
      path: '/api/payments/pabfc/stk/callback'
      fullPath: '/api/payments/pabfc/stk/callback'
      preLoaderRoute: typeof ApiPaymentsPabfcStkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/pabfc/c2b/validate': {
      id: '/api/payments/pabfc/c2b/validate'
      path: '/api/payments/pabfc/c2b/validate'
      fullPath: '/api/payments/pabfc/c2b/validate'
      preLoaderRoute: typeof ApiPaymentsPabfcC2bValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/pabfc/c2b/conf': {
      id: '/api/payments/pabfc/c2b/conf'
      path: '/api/payments/pabfc/c2b/conf'
      fullPath: '/api/payments/pabfc/c2b/conf'
      preLoaderRoute: typeof ApiPaymentsPabfcC2bConfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppBankingsPostingsRouteRouteChildren {
  AppBankingsPostingsNewRoute: typeof AppBankingsPostingsNewRoute
  AppBankingsPostingsIndexRoute: typeof AppBankingsPostingsIndexRoute
  AppBankingsPostingsPostingIdEditRoute: typeof AppBankingsPostingsPostingIdEditRoute
}

const AppBankingsPostingsRouteRouteChildren: AppBankingsPostingsRouteRouteChildren =
  {
    AppBankingsPostingsNewRoute: AppBankingsPostingsNewRoute,
    AppBankingsPostingsIndexRoute: AppBankingsPostingsIndexRoute,
    AppBankingsPostingsPostingIdEditRoute:
      AppBankingsPostingsPostingIdEditRoute,
  }

const AppBankingsPostingsRouteRouteWithChildren =
  AppBankingsPostingsRouteRoute._addFileChildren(
    AppBankingsPostingsRouteRouteChildren,
  )

interface AppBankingsRouteRouteChildren {
  AppBankingsPostingsRouteRoute: typeof AppBankingsPostingsRouteRouteWithChildren
  AppBankingsClearRoute: typeof AppBankingsClearRoute
  AppBankingsReconcilliationRoute: typeof AppBankingsReconcilliationRoute
}

const AppBankingsRouteRouteChildren: AppBankingsRouteRouteChildren = {
  AppBankingsPostingsRouteRoute: AppBankingsPostingsRouteRouteWithChildren,
  AppBankingsClearRoute: AppBankingsClearRoute,
  AppBankingsReconcilliationRoute: AppBankingsReconcilliationRoute,
}

const AppBankingsRouteRouteWithChildren =
  AppBankingsRouteRoute._addFileChildren(AppBankingsRouteRouteChildren)

interface AppBillsRouteRouteChildren {
  AppBillsNewRoute: typeof AppBillsNewRoute
  AppBillsIndexRoute: typeof AppBillsIndexRoute
  AppBillsBillIdEditRoute: typeof AppBillsBillIdEditRoute
}

const AppBillsRouteRouteChildren: AppBillsRouteRouteChildren = {
  AppBillsNewRoute: AppBillsNewRoute,
  AppBillsIndexRoute: AppBillsIndexRoute,
  AppBillsBillIdEditRoute: AppBillsBillIdEditRoute,
}

const AppBillsRouteRouteWithChildren = AppBillsRouteRoute._addFileChildren(
  AppBillsRouteRouteChildren,
)

interface AppChartOfAccountsRouteRouteChildren {
  AppChartOfAccountsNewRoute: typeof AppChartOfAccountsNewRoute
  AppChartOfAccountsIndexRoute: typeof AppChartOfAccountsIndexRoute
  AppChartOfAccountsAccountIdEditRoute: typeof AppChartOfAccountsAccountIdEditRoute
}

const AppChartOfAccountsRouteRouteChildren: AppChartOfAccountsRouteRouteChildren =
  {
    AppChartOfAccountsNewRoute: AppChartOfAccountsNewRoute,
    AppChartOfAccountsIndexRoute: AppChartOfAccountsIndexRoute,
    AppChartOfAccountsAccountIdEditRoute: AppChartOfAccountsAccountIdEditRoute,
  }

const AppChartOfAccountsRouteRouteWithChildren =
  AppChartOfAccountsRouteRoute._addFileChildren(
    AppChartOfAccountsRouteRouteChildren,
  )

interface AppExpensesExpenseIdRouteRouteChildren {
  AppExpensesExpenseIdEditRoute: typeof AppExpensesExpenseIdEditRoute
  AppExpensesExpenseIdViewRoute: typeof AppExpensesExpenseIdViewRoute
}

const AppExpensesExpenseIdRouteRouteChildren: AppExpensesExpenseIdRouteRouteChildren =
  {
    AppExpensesExpenseIdEditRoute: AppExpensesExpenseIdEditRoute,
    AppExpensesExpenseIdViewRoute: AppExpensesExpenseIdViewRoute,
  }

const AppExpensesExpenseIdRouteRouteWithChildren =
  AppExpensesExpenseIdRouteRoute._addFileChildren(
    AppExpensesExpenseIdRouteRouteChildren,
  )

interface AppExpensesRouteRouteChildren {
  AppExpensesExpenseIdRouteRoute: typeof AppExpensesExpenseIdRouteRouteWithChildren
  AppExpensesNewRoute: typeof AppExpensesNewRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
}

const AppExpensesRouteRouteChildren: AppExpensesRouteRouteChildren = {
  AppExpensesExpenseIdRouteRoute: AppExpensesExpenseIdRouteRouteWithChildren,
  AppExpensesNewRoute: AppExpensesNewRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
}

const AppExpensesRouteRouteWithChildren =
  AppExpensesRouteRoute._addFileChildren(AppExpensesRouteRouteChildren)

interface AppFinancialYearsRouteRouteChildren {
  AppFinancialYearsNewRoute: typeof AppFinancialYearsNewRoute
  AppFinancialYearsIndexRoute: typeof AppFinancialYearsIndexRoute
  AppFinancialYearsFinancialYearIdEditRoute: typeof AppFinancialYearsFinancialYearIdEditRoute
}

const AppFinancialYearsRouteRouteChildren: AppFinancialYearsRouteRouteChildren =
  {
    AppFinancialYearsNewRoute: AppFinancialYearsNewRoute,
    AppFinancialYearsIndexRoute: AppFinancialYearsIndexRoute,
    AppFinancialYearsFinancialYearIdEditRoute:
      AppFinancialYearsFinancialYearIdEditRoute,
  }

const AppFinancialYearsRouteRouteWithChildren =
  AppFinancialYearsRouteRoute._addFileChildren(
    AppFinancialYearsRouteRouteChildren,
  )

interface AppMembersRouteRouteChildren {
  AppMembersNewRoute: typeof AppMembersNewRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
  AppMembersMemberIdEditRoute: typeof AppMembersMemberIdEditRoute
  AppMembersMemberIdProfileRoute: typeof AppMembersMemberIdProfileRoute
}

const AppMembersRouteRouteChildren: AppMembersRouteRouteChildren = {
  AppMembersNewRoute: AppMembersNewRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
  AppMembersMemberIdEditRoute: AppMembersMemberIdEditRoute,
  AppMembersMemberIdProfileRoute: AppMembersMemberIdProfileRoute,
}

const AppMembersRouteRouteWithChildren = AppMembersRouteRoute._addFileChildren(
  AppMembersRouteRouteChildren,
)

interface AppPaymentsRouteRouteChildren {
  AppPaymentsNewRoute: typeof AppPaymentsNewRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppPaymentsPaymentIdDetailsRoute: typeof AppPaymentsPaymentIdDetailsRoute
  AppPaymentsPaymentIdEditRoute: typeof AppPaymentsPaymentIdEditRoute
}

const AppPaymentsRouteRouteChildren: AppPaymentsRouteRouteChildren = {
  AppPaymentsNewRoute: AppPaymentsNewRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppPaymentsPaymentIdDetailsRoute: AppPaymentsPaymentIdDetailsRoute,
  AppPaymentsPaymentIdEditRoute: AppPaymentsPaymentIdEditRoute,
}

const AppPaymentsRouteRouteWithChildren =
  AppPaymentsRouteRoute._addFileChildren(AppPaymentsRouteRouteChildren)

interface AppPlansRouteRouteChildren {
  AppPlansNewRoute: typeof AppPlansNewRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
  AppPlansPlanIdEditRoute: typeof AppPlansPlanIdEditRoute
  AppPlansPlanIdRevenueRoute: typeof AppPlansPlanIdRevenueRoute
  AppPlansPlanIdViewMembersRoute: typeof AppPlansPlanIdViewMembersRoute
}

const AppPlansRouteRouteChildren: AppPlansRouteRouteChildren = {
  AppPlansNewRoute: AppPlansNewRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
  AppPlansPlanIdEditRoute: AppPlansPlanIdEditRoute,
  AppPlansPlanIdRevenueRoute: AppPlansPlanIdRevenueRoute,
  AppPlansPlanIdViewMembersRoute: AppPlansPlanIdViewMembersRoute,
}

const AppPlansRouteRouteWithChildren = AppPlansRouteRoute._addFileChildren(
  AppPlansRouteRouteChildren,
)

interface AppReceiptsRouteRouteChildren {
  AppReceiptsNewRoute: typeof AppReceiptsNewRoute
  AppReceiptsIndexRoute: typeof AppReceiptsIndexRoute
  AppReceiptsReceiptIdDetailsRoute: typeof AppReceiptsReceiptIdDetailsRoute
}

const AppReceiptsRouteRouteChildren: AppReceiptsRouteRouteChildren = {
  AppReceiptsNewRoute: AppReceiptsNewRoute,
  AppReceiptsIndexRoute: AppReceiptsIndexRoute,
  AppReceiptsReceiptIdDetailsRoute: AppReceiptsReceiptIdDetailsRoute,
}

const AppReceiptsRouteRouteWithChildren =
  AppReceiptsRouteRoute._addFileChildren(AppReceiptsRouteRouteChildren)

interface AppSuppliersRouteRouteChildren {
  AppSuppliersNewRoute: typeof AppSuppliersNewRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppSuppliersSupplierIdEditRoute: typeof AppSuppliersSupplierIdEditRoute
}

const AppSuppliersRouteRouteChildren: AppSuppliersRouteRouteChildren = {
  AppSuppliersNewRoute: AppSuppliersNewRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppSuppliersSupplierIdEditRoute: AppSuppliersSupplierIdEditRoute,
}

const AppSuppliersRouteRouteWithChildren =
  AppSuppliersRouteRoute._addFileChildren(AppSuppliersRouteRouteChildren)

interface AppUsersRolesRouteRouteChildren {
  AppUsersRolesNewRoute: typeof AppUsersRolesNewRoute
  AppUsersRolesIndexRoute: typeof AppUsersRolesIndexRoute
  AppUsersRolesRoleIdEditRoute: typeof AppUsersRolesRoleIdEditRoute
}

const AppUsersRolesRouteRouteChildren: AppUsersRolesRouteRouteChildren = {
  AppUsersRolesNewRoute: AppUsersRolesNewRoute,
  AppUsersRolesIndexRoute: AppUsersRolesIndexRoute,
  AppUsersRolesRoleIdEditRoute: AppUsersRolesRoleIdEditRoute,
}

const AppUsersRolesRouteRouteWithChildren =
  AppUsersRolesRouteRoute._addFileChildren(AppUsersRolesRouteRouteChildren)

interface AppUsersRouteRouteChildren {
  AppUsersRolesRouteRoute: typeof AppUsersRolesRouteRouteWithChildren
  AppUsersNewRoute: typeof AppUsersNewRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppUsersUserIdEditRoute: typeof AppUsersUserIdEditRoute
  AppUsersUserIdResetRoute: typeof AppUsersUserIdResetRoute
}

const AppUsersRouteRouteChildren: AppUsersRouteRouteChildren = {
  AppUsersRolesRouteRoute: AppUsersRolesRouteRouteWithChildren,
  AppUsersNewRoute: AppUsersNewRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppUsersUserIdEditRoute: AppUsersUserIdEditRoute,
  AppUsersUserIdResetRoute: AppUsersUserIdResetRoute,
}

const AppUsersRouteRouteWithChildren = AppUsersRouteRoute._addFileChildren(
  AppUsersRouteRouteChildren,
)

interface AppReportsFinanceRouteRouteChildren {
  AppReportsFinanceIndexRoute: typeof AppReportsFinanceIndexRoute
  AppReportsFinanceBankingIndexRoute: typeof AppReportsFinanceBankingIndexRoute
  AppReportsFinanceExpensesIndexRoute: typeof AppReportsFinanceExpensesIndexRoute
  AppReportsFinanceIncomeStatementIndexRoute: typeof AppReportsFinanceIncomeStatementIndexRoute
  AppReportsFinanceInvoicesIndexRoute: typeof AppReportsFinanceInvoicesIndexRoute
  AppReportsFinancePaymentsIndexRoute: typeof AppReportsFinancePaymentsIndexRoute
  AppReportsFinanceReceiptsIndexRoute: typeof AppReportsFinanceReceiptsIndexRoute
  AppReportsFinanceTrialBalanceIndexRoute: typeof AppReportsFinanceTrialBalanceIndexRoute
}

const AppReportsFinanceRouteRouteChildren: AppReportsFinanceRouteRouteChildren =
  {
    AppReportsFinanceIndexRoute: AppReportsFinanceIndexRoute,
    AppReportsFinanceBankingIndexRoute: AppReportsFinanceBankingIndexRoute,
    AppReportsFinanceExpensesIndexRoute: AppReportsFinanceExpensesIndexRoute,
    AppReportsFinanceIncomeStatementIndexRoute:
      AppReportsFinanceIncomeStatementIndexRoute,
    AppReportsFinanceInvoicesIndexRoute: AppReportsFinanceInvoicesIndexRoute,
    AppReportsFinancePaymentsIndexRoute: AppReportsFinancePaymentsIndexRoute,
    AppReportsFinanceReceiptsIndexRoute: AppReportsFinanceReceiptsIndexRoute,
    AppReportsFinanceTrialBalanceIndexRoute:
      AppReportsFinanceTrialBalanceIndexRoute,
  }

const AppReportsFinanceRouteRouteWithChildren =
  AppReportsFinanceRouteRoute._addFileChildren(
    AppReportsFinanceRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppBankingsRouteRoute: typeof AppBankingsRouteRouteWithChildren
  AppBillsRouteRoute: typeof AppBillsRouteRouteWithChildren
  AppChartOfAccountsRouteRoute: typeof AppChartOfAccountsRouteRouteWithChildren
  AppExpensesRouteRoute: typeof AppExpensesRouteRouteWithChildren
  AppFinancialYearsRouteRoute: typeof AppFinancialYearsRouteRouteWithChildren
  AppMembersRouteRoute: typeof AppMembersRouteRouteWithChildren
  AppPaymentsRouteRoute: typeof AppPaymentsRouteRouteWithChildren
  AppPlansRouteRoute: typeof AppPlansRouteRouteWithChildren
  AppReceiptsRouteRoute: typeof AppReceiptsRouteRouteWithChildren
  AppSuppliersRouteRoute: typeof AppSuppliersRouteRouteWithChildren
  AppUsersRouteRoute: typeof AppUsersRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppJournalEntriesRoute: typeof AppJournalEntriesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUnauthorizedRoute: typeof AppUnauthorizedRoute
  AppReportsFinanceRouteRoute: typeof AppReportsFinanceRouteRouteWithChildren
  AppActivityLogsIndexRoute: typeof AppActivityLogsIndexRoute
  AppAttendancesIndexRoute: typeof AppAttendancesIndexRoute
  AppCommunicationIndexRoute: typeof AppCommunicationIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBankingsRouteRoute: AppBankingsRouteRouteWithChildren,
  AppBillsRouteRoute: AppBillsRouteRouteWithChildren,
  AppChartOfAccountsRouteRoute: AppChartOfAccountsRouteRouteWithChildren,
  AppExpensesRouteRoute: AppExpensesRouteRouteWithChildren,
  AppFinancialYearsRouteRoute: AppFinancialYearsRouteRouteWithChildren,
  AppMembersRouteRoute: AppMembersRouteRouteWithChildren,
  AppPaymentsRouteRoute: AppPaymentsRouteRouteWithChildren,
  AppPlansRouteRoute: AppPlansRouteRouteWithChildren,
  AppReceiptsRouteRoute: AppReceiptsRouteRouteWithChildren,
  AppSuppliersRouteRoute: AppSuppliersRouteRouteWithChildren,
  AppUsersRouteRoute: AppUsersRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppJournalEntriesRoute: AppJournalEntriesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUnauthorizedRoute: AppUnauthorizedRoute,
  AppReportsFinanceRouteRoute: AppReportsFinanceRouteRouteWithChildren,
  AppActivityLogsIndexRoute: AppActivityLogsIndexRoute,
  AppAttendancesIndexRoute: AppAttendancesIndexRoute,
  AppCommunicationIndexRoute: AppCommunicationIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface MemberRouteRouteChildren {
  MemberDashboardRoute: typeof MemberDashboardRoute
  MemberLoginRoute: typeof MemberLoginRoute
}

const MemberRouteRouteChildren: MemberRouteRouteChildren = {
  MemberDashboardRoute: MemberDashboardRoute,
  MemberLoginRoute: MemberLoginRoute,
}

const MemberRouteRouteWithChildren = MemberRouteRoute._addFileChildren(
  MemberRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  MemberRouteRoute: MemberRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCommunicationsGetMembersRoute: ApiCommunicationsGetMembersRoute,
  ApiUploadsExpenseAttachmentRoute: ApiUploadsExpenseAttachmentRoute,
  ApiInngestIndexRoute: ApiInngestIndexRoute,
  ApiMockApiIndexRoute: ApiMockApiIndexRoute,
  ApiCronDailyIndexRoute: ApiCronDailyIndexRoute,
  ApiPaymentsPabfcC2bConfRoute: ApiPaymentsPabfcC2bConfRoute,
  ApiPaymentsPabfcC2bValidateRoute: ApiPaymentsPabfcC2bValidateRoute,
  ApiPaymentsPabfcStkCallbackRoute: ApiPaymentsPabfcStkCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
